### ISSUE TITLE
Add PR checks to validate new entries and whatnot

### ISSUE THREAD

**Issue by interrrp** [letsbuilda/shills#6]
```[tasklist]
### Tasks
- [ ] Ensure that JSON is valid and formatted correctly
- [ ] Ensure that only one entry was added
- [ ] Ensure that the entry's name matches the author's GitHub username (maybe impossible, but we'll see)
```
